mysite/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^contact/', views.contact, name='contact'),
    url(r'^projects/', views.projects_listing, name='projects_listing'),
    url(r'^project/(?P<pk>\d+)/', views.project_detail, name='project_detail'),
    url(r'^about/', views.about, name='about'),
    url(r'^post/(?P<pk>\d+)/', views.post_detail, name='post_detail'),
    url(r'^$', views.posts_listing, name='posts_listing'),
]

mysitedjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('mysite.urls', namespace='mysite'))
]

mysite/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    posted_at = models.DateTimeField(auto_now_add=True)
    is_draft = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Project(models.Model):
    title = models.CharField(max_length=255)
    link = models.URLField()
    description = models.TextField()
    is_draft = models.BooleanField(default=True)
    posted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

mysite/forms.py
from django import forms


class Contact(forms.Form):
    name = forms.CharField(label='Name')
    email = forms.EmailField(label='Email')
    body = forms.CharField(widget=forms.Textarea, label='Body')

mysite/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.safestring import mark_safe
from mysitedjango.settings import SENDGRID_PASSWORD, SENDGRID_USERNAME
from .models import Post, Project
from .forms import Contact
from markdown import markdown

import sendgrid

SENDGRID = sendgrid.SendGridClient(SENDGRID_USERNAME, SENDGRID_PASSWORD)

def posts_listing(request):
    posts = Post.objects.all()
    return render(request, 'mysite/posts_listing.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    html_body = mark_safe(markdown(post.body))
    return render(request, 'mysite/post_detail.html', {'post': post, 'html_body': html_body})


def projects_listing(request):
    projects = Project.objects.all()
    return render(request, 'mysite/projects_listings.html', {'projects': projects})


def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    html_description = mark_safe(markdown(project.description))
    return render(request, 'mysite/project_detail.html', {'project': project, 'html_description': html_description})


def about(request):
    return render(request, 'mysite/about.html')


def contact(request):
    if request.POST:
        message = sendgrid.Mail()
        message.add_to('charlie.thomas@attwoodthomas.net')
        message.set_subject(request.POST['name'])
        message.set_text(request.POST['body'])
        message.set_from(request.POST['email'])

        try:
            SENDGRID.send(message)
            print("Sent")
        except sendgrid.SendGridClientError:
            print("Client Error")
        except sendgrid.SendGridServerError:
            print("Server Error")

    form = Contact(auto_id='%s')
    return render(request, 'mysite/contact.html', {'form': form})
    pass

mysite/templates/mysite/about.html
{% extends "layout.html" %}
{% block body %}
    <h3>About</h3>
    <p>
        Hello, I'm Charlie Thomas. I love programming, model rocketry, food and being a nerd. Find me around the web as Ottermad.
    </p>
    <p>
        I am a backend and frontend developer with experience in Python and Flask, Java and Android Developement, PHP, HTML, CSS and Javascript.
    </p>
    <p>
        If you would like to follow me on Twitter, my username is 
        <a href="https://twitter.com/AttwoodCharlie">
            @AttwoodCharlie
        </a>
    </p>
    <p>
        If you like my website, please like it:
    </p>
    <div class="fb-like" data-href="http://attwoodthomas.me" data-width="100" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
{% endblock %}

mysite/templates/mysite/contact.html
{% extends 'layout.html' %}
{% block body %}
    <h3>Contact Me</h3>
    <p>
        Please feel free to contact me if you have any questions, or are looking for a web developer.
        <br>
        Contact me using the form below or using one of the methods also listed.
    </p>
    <section id="contact-form">
        <form method="POST" class="form">
            {% csrf_token %}
            <fieldset>
                {{ form.name.label_tag }}
                {{ form.name }}
            </fieldset>
            <fieldset>
                {{ form.email.label_tag }}
                {{ form.email }}
            </fieldset>
            <fieldset>
                {{ form.body.label_tag }}
                {{ form.body }}
            </fieldset>
            <fieldset>
                <button type="submit" id="submit" class="btn btn-success btn-lg">Contact Me!</button>
            </fieldset>
        </form>
    </section>
    <section id="contact-details">
        <ul>
            <li>Twitter: <a href="https://twitter.com/AttwoodCharlie">@AttwoodCharlie</a></li>
            <li>Google Plus: <a href="https://plus.google.com/u/0/103227713602162942632">https://plus.google.com/u/0/103227713602162942632</a></li>
            <li>Github: <a href="https://github.com/Ottermad">Ottermad</a></li>
            <li>Email: <a href="mailto:charlie.thomas@attwoodthomas.net">charlie.thomas@attwoodthomas.net</a></li>
            <li>Phone: <a href="tel:+447795958759">+447795958758</a></li>
        </ul>
    </section>

{% endblock %}

mysite/templates/mysite/post_detail.html
{% extends "layout.html" %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block body %}
    <h3>
        {{ post.title }}
        <br>
        <small class="date">{{ post.posted_at }}</small>
    </h3>

    {{ html_body }}
    <div id="shareButtons">
        <div class="fb-like" data-href="{{ url }}" data-width="100" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
        <br>
        <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </div>
    <button class="btn btn-info btn-lg" onclick="location.href='{% url 'mysite:posts_listing' %}'">
        Go Back
    </button>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'attwoodthomas'; // required: replace example with your forum shortname
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

{% endblock %}

mysite/templates/mysite/posts_listing.html
{% extends "layout.html" %}
{% block body %}
    <h3>Posts</h3>
    <table id="posts-table">
        <tbody>
            {% for post in posts %}
                <tr>
                    <td>
                        {{ post.title }} - {{ post.posted_at }}
                    </td>

                    <td>
                        <button class="btn btn-info btn-lg" onclick="location.href='{% url 'mysite:post_detail' pk=post.pk %}'">
                            View
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mysite/templates/mysite/project_detail.html
{% extends "layout.html" %}
{% block title %}
    {{ project.title }}
{% endblock %}
{% block body %}
    <h3>
        {{ project.title }}
        <br>
        <small class="date">{{ project.posted_at }}</small>
    </h3>

    <a href="{{ project.link }}">{{ project.link }}</a>

    {{ html_description }}

    <button class="btn btn-info btn-lg" onclick="location.href='{% url 'mysite:projects_listing' %}'">
        Go Back
    </button>
{% endblock %}

mysite/templates/mysite/projects_listings.html
{% extends "layout.html" %}
{% block body %}
	<h3>Projects</h3>
    <ul id="portfolio-listing">

        {% for project in projects %}
            <li>
                <ul>
                    <li>{{ project.title }}</li>
                    <li>
                        <a href="{{ project.link }}" class="projectLink" style="word-wrap: break-word;">
                            {{ project.link }}
                        </a>
                    </li>
                    <li>
                        <a class="btn btn-info view-btn" role="button" href="{% url 'mysite:project_detail' pk=project.pk %}">
                          View Description
                        </a>
                   </li>
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/layout.html
{% load static from staticfiles  %}
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Charles Thomas">
        <meta name="description" content="The personal blog and site of a teenage developer.">
        <link href='http://fonts.googleapis.com/css?family=Arvo:400,400italic' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>{% block title %}Charles Thomas | Developer {% endblock %}</title>
        <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.min.css" />
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=644334525693753&version=v2.3";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <div id="wrap">
            <header>
                <nav id="site-nav">
                    <h1>Charles Thomas</h1>
                    <div class="v-wrap">
                        <div class="v-box">
                            <ul class="">
                                <li>
                                    <a href="{% url 'mysite:posts_listing' %}">
                                        BLOG
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'mysite:about' %}">
                                        ABOUT
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'mysite:projects_listing' %}">
                                        PORTFOLIO
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'mysite:contact' %}">
                                        CONTACT
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>

            </header>
            <div class="main">
                {% block body %}
                {% endblock %}
            </div>
        </div>
        <footer>
            <p class="footer">
                &copy; Charles Thomas 2015
            </p>
        </footer>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
        {% block extra_js %}
        {% endblock %}
    </body>
</html>